<?php

namespace Mythos\Core\Support\Deprecation;

use Mythos\Core\Support\Api\Deprecated;
use ReflectionClass;
use ReflectionMethod;

final class DeprecationRegistry
{
    /** @return list<array{symbol: string, since: string, replacement: string, removal: string, reason: ?string}> */
    public function all(): array
    {
        $deprecations = [];
        $classMap = require base_path('vendor/composer/autoload_classmap.php');

        foreach (array_keys($classMap) as $class) {
            if (! str_starts_with($class, 'Mythos\\Core\\') || ! class_exists($class) && ! interface_exists($class) && ! enum_exists($class)) {
                continue;
            }

            $reflection = new ReflectionClass($class);
            $this->collectAttributes($deprecations, $reflection->getName(), $reflection->getAttributes(Deprecated::class));

            foreach ($reflection->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
                if ($method->getDeclaringClass()->getName() !== $reflection->getName()) {
                    continue;
                }

                $this->collectAttributes(
                    $deprecations,
                    $reflection->getName().'::'.$method->getName().'()',
                    $method->getAttributes(Deprecated::class),
                );
            }
        }

        usort($deprecations, fn (array $left, array $right) => $left['symbol'] <=> $right['symbol']);

        return $deprecations;
    }

    public function markdown(): string
    {
        $lines = [
            '# Mythos OS deprecations',
            '',
            'Generated by `php artisan mythos:deprecations --write`.',
            '',
        ];
        $deprecations = $this->all();

        if ($deprecations === []) {
            $lines[] = 'Mythos OS v1.0.0 contains no deprecated public APIs.';

            return implode(PHP_EOL, $lines).PHP_EOL;
        }

        $lines[] = '| Symbol | Since | Replacement | Removal | Reason |';
        $lines[] = '|---|---|---|---|---|';

        foreach ($deprecations as $deprecation) {
            $lines[] = sprintf(
                '| `%s` | %s | `%s` | %s | %s |',
                $deprecation['symbol'],
                $deprecation['since'],
                $deprecation['replacement'],
                $deprecation['removal'],
                $deprecation['reason'] ?? '—',
            );
        }

        return implode(PHP_EOL, $lines).PHP_EOL;
    }

    private function collectAttributes(array &$deprecations, string $symbol, array $attributes): void
    {
        foreach ($attributes as $attribute) {
            /** @var Deprecated $deprecation */
            $deprecation = $attribute->newInstance();
            $deprecations[] = [
                'symbol' => $symbol,
                'since' => $deprecation->since,
                'replacement' => $deprecation->replacement,
                'removal' => $deprecation->removalVersion,
                'reason' => $deprecation->reason,
            ];
        }
    }
}
